### ISSUE TITLE
errors installing on ubuntu 16.04

### ISSUE THREAD

**Issue by scotty770** [endgameinc/xori#12]
![screenshot from 2018-08-16 13-30-13](https://user-images.githubusercontent.com/26236902/44208568-9abbe800-a158-11e8-873a-86af9d955a6b.png)

**Comment by d1maz** [comment]
hey @scotty770 - this is because your rust version is below the required **rustc 1.27.0** see [here](https://github.com/endgameinc/xori#requirements)

check it with **rustc --version**
