### ISSUE TITLE
Info: Dependency list (Ubuntu 18.04 WKS default install)

### ISSUE THREAD

**Issue by CMDR-Nexus** [endgameinc/xori#3]
curl git libssl-dev pkg-config build-essential npm

**Comment by rseymour** [comment]
I'll try to put this in as an installation footnote.  Were you using rust from rustup.rs or somewhere else?

**Comment by CMDR-Nexus** [comment]
Rust installed as per installation guide using sh.rustup.rs

**Comment by rseymour** [comment]
radical. ok yolo editing our readme

**Comment by rseymour** [comment]
fixed in readme
