### ISSUE TITLE
issue with Browser GUI

### ISSUE THREAD

**Issue by Frenchy7** [endgameinc/xori#8]
I get an error when I try to parse a file :
![screenshot_2](https://user-images.githubusercontent.com/33000544/44065465-27979a0c-9f6b-11e8-87c4-945ba3725f7a.png)

I use Chrome on Windows 10.

**Comment by rseymour** [comment]
Did you copy the example xori.json.example over to xori.json?

Other thing to check is did you run 

```
cd gui
node src/server.js
```
in another terminal?

**Comment by Frenchy7** [comment]
I had actually launched a terminal. Sorry for your time @rseymour .

**Comment by Frenchy7** [comment]
I had actually launched only one terminal. But i get the same error with two terminal :
![screenshot_3](https://user-images.githubusercontent.com/33000544/44090107-541b4ad4-9fc9-11e8-9f34-4becf0379449.png)
Thx for your time @rseymour .
